name: IPFS Preview Deploy
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ipfs-preview-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Inject slug variables
        uses: rlespinasse/github-slug-action@3.5.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{secrets.GITHUB_TOKEN}}
          env: ${{env.GITHUB_HEAD_REF_SLUG_URL || env.GITHUB_REF_SLUG_URL}}
          ref: ${{github.head_ref}}
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: ipfs-build
        env:
          REACT_APP_FACTORY_ADDRESS_ARBITRUM_ONE: '0x359F20Ad0F42D75a5077e65F30274cABe6f4F01a'
          REACT_APP_ROUTER_ADDRESS_ARBITRUM_ONE: '0x530476d5583724A89c8841eB6Da76E7Af4C0F17E'
          REACT_APP_STAKING_REWARDS_FACTORY_ADDRESS_ARBITRUM_ONE: '0xecA7F78d59D16812948849663b26FE10E320f80C'
          REACT_APP_SWPR_ADDRESS_ARBITRUM_ONE: '0xdE903E2712288A1dA82942DDdF2c20529565aC30'
          REACT_APP_SWPR_ADDRESS_MAINNET: '0x6cAcDB97e3fC8136805a9E7c342d866ab77D0957'
          REACT_APP_SWPR_CLAIMER_ADDRESS_ARBITRUM_ONE: '0xe54942077Df7b8EEf8D4e6bCe2f7B58B0082b0cd'
          REACT_APP_SWPR_AIRDROP_WHITELIST_IPFS_HASH: 'QmcjTAvDJZU339jrc9Ky2pXKR68R1SjnwdyGSQjt1kad9r'
          REACT_APP_SWPR_CONVERTER_ADDRESS_ARBITRUM_ONE: '0x2b058af96175A847Bf3E5457B3A702F807daDdFd'
      - name: Deploy to IPFS
        uses: web3-storage/add-to-web3@v1
        id: web3
        with:
          web3_token: ${{secrets.WEB3_STORAGE_TOKEN}}
          path_to_add: 'build'
      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.6.0
        if: always()
        with:
          step: finish
          token: ${{secrets.GITHUB_TOKEN}}
          status: ${{job.status}}
          deployment_id: ${{steps.deployment.outputs.deployment_id}}
          env_url: 'https://${{steps.web3.outputs.cid}}.ipfs.dweb.link'
